language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "nightly"  # nightly build
# command to install dependencies
#install:
  #- pip install -r requirements.txt
# command to run tests

jobs:
  include:
    - stage: test
      script: pytest src/HelloWorld.py
    - # stage name not required, will continue to use `test`
      script: pytest src/HelloWorld.py
    - stage: deploy #not really deploy
      script: pytest src/HelloWorld.py
      